### ISSUE TITLE
Support for WiPro Home Lights

### ISSUE THREAD

**Issue by FadedCoder** [RGBKit/rgbkit#2]
Sync support for https://www.wiproconsumerlighting.com/smartled

Cannot find official API, might have to reverse engineer phone app.

EDIT #1: Supports IFTTT
EDIT #2: Uses Tuya.com licensed. https://github.com/codetheweb/tuyapi should work.

**Comment by AndrewBabbitt97** [comment]
Wont personally be implementing this, seeing as no one has started this will close for the time being. Feel free to reopen if discussions start on this.
