### ISSUE TITLE
'RGBKitService' does not contain a definition for 'UseAura'

### ISSUE THREAD

**Issue by tew515** [RGBKit/rgbkit#4]
Using the sample code: https://github.com/RGBKit/rgbkit/wiki/Getting-Started

![image](https://user-images.githubusercontent.com/67100537/88564860-aba35280-d02b-11ea-87c0-a3ded9eb1779.png)

I get the error: CS1061 - 'RGBKitService' does not contain a definition for 'UseAura' and no accessible extension method 'UseAura' accepting a first argument of type 'RGBKitService' could be found (are you missing a using directive or an assembly reference?)

Any help would be appreciated. Thank you.

**Comment by AndrewBabbitt97** [comment]
You probably need a package reference to RGBKit.Providers.Aura where the UseAura extension method resides

**Comment by tew515** [comment]
.Providers does not exist in the namespace

**Comment by tew515** [comment]
The packages are not all installed at once but separately. https://www.nuget.org/packages/RGBKit.Providers.Aura/ and https://www.nuget.org/packages/RGBKit.Providers.Cue/
