### ISSUE TITLE
Initialize() method hangs forever

### ISSUE THREAD

**Issue by Inventor22** [RGBKit/RGBKit#6]
Using the Getting Started example, replacing UseAura() method with UseCue(), the Initialize() method hangs forever. iCue software is running, full software control is enabled for RGB RAM.

Any ideas? Thanks.

        static void Main(string[] args)
        {
            //Create the service
            var rgbKit = new RGBKitService();

            //Use any device providers
            //Must be done before initializing the service
            rgbKit.UseCue();

            //Initialization may take some time depending on device provider initialization requirements
            Console.WriteLine("Initializing...");

            //Initialize the service
            rgbKit.Initialize();

            //Loop through the device providers
            foreach (var provider in rgbKit.DeviceProviders)
            {
                //You can get the provider name
                Console.WriteLine($"Provider: {provider.Name}");

                //Loop through the devices in the provider
                foreach (var device in provider.Devices)
                {
                    //You can get the device name
                    Console.WriteLine($"Device: {device.Name}");

                    //Loop through the lights in the device
                    foreach (var light in device.Lights)
                    {
                        //Set the light color
                        light.Color = Color.FromArgb(0, 0, 255);
                    }

                    //Apply the changes to the lights
                    device.ApplyLights();
                }
            }

            //Wait
            Console.ReadLine();
        }

**Comment by AndrewBabbitt97** [comment]
Sorry late on getting to this. I have just uploaded updated NuGet packages using the latest CUE SDK. I have tested this very code and its working on my side.
